-- Longer, human-style customer reviews (Bangla + English mix)

DELETE FROM reviews;

INSERT INTO reviews (product_id, reviewer_name, rating, comment, is_verified, created_at)
SELECT p.id, d.reviewer_name, d.rating, d.comment, d.is_verified, d.created_at
FROM products p
INNER JOIN (
  VALUES
    (1, 'রাহেলা বেগম', 5, 'আমি প্রায় এক সপ্তাহ ধরে বিভিন্ন দোকানে ভালো আয়াতুল কুরসি ক্যানভাস খুঁজছিলাম। WallNest থেকে অর্ডার করার পর তিন দিনের মধ্যে হাতে পেলাম। কাপড় মোটা, স্টিচ পরিষ্কার, রঙ একদম ছবির মতো উজ্জ্বল। ড্রয়িং রুমের হালকা নীল দেয়ালে লাগানোর পর পুরো ঘর শান্ত ও পরিচ্ছন্ন লাগে। বাবা-মাও এসে দেখে বললেন অনেক সুন্দর হয়েছে। প্যাকেজিং যত্নসহকারে ছিল — কোনো ভাঁজ বা দাগ নেই। দাম অনুযায়ী মান একদম ঠিক, আবার নেব।', true, NOW() - INTERVAL '52 days'),
    (1, 'Tanvir Hossain', 5, 'Ordered this Ayatul Kursi canvas for our new flat in Mirpur. Delivery was faster than I expected and the print is genuinely sharp — you can read the Arabic clearly even from across the room. The frame feels solid and the colours did not look washed out in daylight. My wife was unsure about buying online but now she wants one for the bedroom too. Packaging had corner protectors so nothing bent in transit. Happy to recommend WallNest to friends.', true, NOW() - INTERVAL '48 days'),
    (2, 'ফারজানা আক্তার', 5, 'বিসমিল্লাহ মেটাল আর্ট লাইভিং রুমে এত সুন্দর লাগছে যে অতিথিরা জিজ্ঞেস করছে কোথা থেকে নিয়েছি। মেটালের ফিনিশ মোটা, হাত দিলে প্রিমিয়াম লাগে। ইনস্টল করতে গাইড ছিল, আমার ভাই ২০ মিনিটে লাগিয়ে দিয়েছে। সন্ধ্যায় লাইট পড়লে হালকা চকচকে দেখায় কিন্তু চোখে অস্বস্তি হয় না। গিফট হিসেবেও দেওয়ার মতো প্রোডাক্ট।', true, NOW() - INTERVAL '45 days'),
    (2, 'Imran Khan', 4, 'Overall very satisfied with the Bismillah metal piece. Finish looks premium and it sits flat on the wall without wobble. Only small note: mounting screws could be labelled in the bag so you do not mix sizes. Took me a few extra minutes to figure out. Customer support replied on WhatsApp within an hour though, which I appreciated. Would still buy again for the guest room.', true, NOW() - INTERVAL '41 days'),
    (3, 'সাবরিনা খান', 5, 'কাবা নাইট স্কাই ক্যানভাসের গভীর নীল আর স্টারের কাজ দেখে মন শান্ত হয়। আমি সিলেট থেকে অর্ডার করেছিলাম, এক সপ্তাহের মধ্যে পেয়েছি। প্রিন্টে কোনো ঝাপসা অংশ নেই, রাতের ল্যাম্পের নরম আলোতে আরও সুন্দর লাগে। দেয়ালের সাইজের জন্য সাইজ গাইড ফলো করেছিলাম, ফিট পারফেক্ট। পরিবারের সবাই খুশি।', true, NOW() - INTERVAL '39 days'),
    (3, 'Rafiul Islam', 4, 'Beautiful night theme and the Kaaba silhouette is respectful, not flashy. Print quality is good for the price. Delivery inside Dhaka was four working days — acceptable. Box had a small dent on the outside but canvas was fine inside the bubble wrap. Hung it in the prayer space and it feels calm. Four stars only because I wanted a slightly larger size option on the site.', true, NOW() - INTERVAL '36 days'),
    (4, 'মাহমুদ হাসান', 5, 'ট্রিপটিচ সেট ওয়াইড ওয়ালে একদম ব্যালান্সড লাগছে। তিন প্যানেলের রঙ মিল আছে, গ্যাপ ঠিক রেখে লাগালে প্যানোরামা ইফেক্ট দারুণ। UV প্রিন্ট বলেছিল, রোদে পড়ে কয়েক সপ্তাহ হয় এখনও রঙ হালকা হয়নি। ইনস্টলেশন কিট পেয়েছি, লেভেল ধরে রাখতে সুবিধা হয়েছে। অফিসের কেউ দেখে বাড়িতেও অর্ডার করেছে।', true, NOW() - INTERVAL '34 days'),
    (4, 'Nusrat Jahan', 5, 'We put the triptych above the sofa and it completely changed the room. Colours are rich and the panels line up if you follow the spacing guide. I was worried about fading near the window but so far no issue after two months. Customer photos on the site matched what we received — no surprise. Thank you WallNest for careful packing.', true, NOW() - INTERVAL '31 days'),
    (5, 'আয়েশা সিদ্দিকা', 5, 'LED ক্যানভাস রাতে বেডরুমে আলাদা মুড দেয়, খুব পছন্দ হয়েছে। আলো খুব তীব্র নয়, চোখে বিরক্ত করে না, রিমোট দিয়ে ডিম করা যায়। ক্যানভাস মোটা, দেয়ালে ঝুললে ভালো লাগে। বাচ্চারা প্রথমে খেলতে চেয়েছিল, এখন শোভা পায়। ইনস্টল করতে ১৫ মিনিট লেগেছে, প্লাগ পয়েন্ট কাছে রাখলে ভালো।', true, NOW() - INTERVAL '29 days'),
    (5, 'Shuvo Das', 4, 'LED feature works as advertised and the adapter is included. Canvas thickness is decent — does not feel cheap. Light is warm white, good for evening. Took one star off because the remote batteries were not included and I had to buy separately. Still, for the price the wow factor is there when guests visit.', true, NOW() - INTERVAL '26 days'),
    (6, 'জাহিদুল ইসলাম', 4, 'অ্যাক্রিলিক ৩D লেটার সহজে লাগানো গেছে, সাইজ সাইটে দেখানোর মতোই এসেছে। দেয়ালে ছায়া পড়ে প্রিমিয়াম লুক দেয়। একটা লেটারে প্রোটেক্টিভ ফিল্ম ছিল, তুলে ফেলার পর চকচকে। নাম স্পেলিং ডাবল চেক করেছিলাম, ঠিক দিয়েছে। দুই সপ্তাহ ব্যবহারে কোনো পড়ে যায়নি।', true, NOW() - INTERVAL '24 days'),
    (6, 'Priya Sharma', 5, 'The 3D letters look classy on our prayer corner wall. We ordered the acrylic finish and it catches soft light without glare. Installation template helped my husband align everything. Visitors often ask where we got it. Feels more expensive than it was. Very happy with WallNest communication before delivery.', true, NOW() - INTERVAL '22 days'),
    (7, 'রুমা বেগম', 5, 'রমজান ল্যান্টার্ন সেট গেস্ট রুমে লাগানোর পর সবাই প্রশংসা করেছে। কাগজের মান ভালো, রঙ উজ্জ্বল কিন্তু cheap লাগে না। বাচ্চারা ল্যান্টার্ন দেখে খুশি, ছোট বাতি দিয়ে সন্ধ্যায় অন্য রকম লাগে। প্যাকেজে আলাদা করে বাবলে রাখা ছিল। পরের রমজানে আরও নেব ইনশাআল্লাহ।', true, NOW() - INTERVAL '20 days'),
    (7, 'Arif Mahmud', 4, 'Seasonal design is lovely and colours fit Ramadan decor. Easy to hang with the hooks provided. Would buy again next year if new designs come. Delivery was before Ramadan week which was important for us. Minor crease on one lantern edge but not visible from distance.', true, NOW() - INTERVAL '18 days'),
    (8, 'সালমা খাতুন', 5, 'ফ্রেমড প্রিন্ট গিফট বক্সসহ এসেছে — বোনকে জন্মদিনে দিয়েছি, কেঁদে খুশি হয়েছে। গ্লাস ফ্রেম মজবুত, প্রিন্ট সেন্টারে, কোনো ঝাপসা নেই। রিবন আর গ্রিটিং কার্ড যোগ করেছিলাম নোটে, তারা সেটাও ঠিকমতো বসিয়ে দিয়েছে। উপহার হিসেবে দেওয়ার জন্য আদর্শ, দামও যুক্তিসঙ্গত।', true, NOW() - INTERVAL '17 days'),
    (8, 'David Chen', 5, 'Glass frame feels solid and the print is crisp. I ordered from Chittagong and it arrived in six days well packed. Edges of the frame have small protectors during shipping. Gave it to my in-laws and they displayed it immediately. Professional look for living room wall art.', true, NOW() - INTERVAL '15 days'),
    (9, 'Karim Ahmed', 5, 'Custom family canvas — we sent a wedding photo and were nervous about quality. WallNest sent a preview link before printing which saved us from a spelling mistake. Final 24x36 print is sharp, skin tones natural, no weird filters. Hung in the hallway and relatives recognise faces clearly. Fast delivery to Gazipur.', true, NOW() - INTERVAL '14 days'),
    (9, 'নাজমা পারভীন', 5, '২৪x৩৬ সাইজে ফটো একদম ক্লিয়ার, রঙ হারায়নি। আমি মা-বাবার পুরনো স্টুডিও ফটো পাঠিয়েছিলাম, রিস্টোর করে দিয়েছে মনে হয় — ক্র্যাক কমে গেছে। ক্যানভাসের কিনারা পরিষ্কার সেলাই। বাড়ির সবচেয়ে মূল্যবান দেয়াল এখন এটা। ধন্যবাদ WallNest টিম।', true, NOW() - INTERVAL '12 days'),
    (10, 'তানিয়া রহমান', 5, 'বিয়ের কাপল ক্যানভাস উপহার হিসেবে দিয়েছিলাম — বন্ধু বললো সেরা গিফট। টেমপ্লেট রোমান্টিক কিন্তু ভ্যালগার নয়, স্টাইলিশ। নাম ও তারিখ ঠিক ছিল। প্যাকিং গিফট রেডি, শুধু রিবন লাগাতে হয়েছে। অনুষ্ঠানের আগে দুই দিনে পেয়েছি, স্ট্রেস কমেছে।', true, NOW() - INTERVAL '11 days'),
    (10, 'James Wilson', 4, 'Template layout is romantic and print quality good. Took about a week to arrive outside Dhaka which is fair. Couple photo colours look warm not orange. Would suggest clearer ETA on checkout for division areas. Product itself exactly as described.', true, NOW() - INTERVAL '10 days'),
    (11, 'রেহানা আক্তার', 5, 'মেমোরিয়াল কোলাজ দেখে চোখে জল এসেছে — খুব সুন্দর ও সম্মানজনক কাজ। ছবিগুলো ভিন্টেজ ফিল্টারে natural লাগে, over-edited নয়। বোনের জন্য বানিয়েছিলাম, পরিবারের সবাই বললো মানানসই। প্রিন্ট মোটা, ফ্রেম ঠিকমতো ফিট। WallNest টিম ফোন করে স্পেলিং কনফার্ম করেছিল, সেটা ভালো লেগেছে।', true, NOW() - INTERVAL '9 days'),
    (11, 'Kabir Hossain', 5, 'Vintage filter on collage photos looks natural. Six photos arranged nicely with names and dates we provided. Packaging was double boxed. Hung in the family room — quiet, respectful piece. Support answered my questions about file format patiently.', true, NOW() - INTERVAL '8 days'),
    (12, 'মিথিলা চৌধুরী', 5, 'বেবি ফুটপ্রিন্ট ক্যানভাস নার্সারিতে ঠিক মতো মানিয়েছে। পেস্টেল রঙ নরম, চোখ ধরে না। নামের বানান ঠিক, তারিখ সুন্দর ফন্টে। আমার মা বললো এটা বছরের সেরা গিফট। কাপড়ে দাগ নেই, ঝুলানোর পরও ঝুলছে সোজা।', true, NOW() - INTERVAL '7 days'),
    (12, 'Samira Khatun', 4, 'Pastel theme is soft and cute for our daughter room. Name spelling was correct which was my main worry. Canvas lighter than expected but still good. Delivery three days in Narayanganj. Would love more colour theme options on website.', true, NOW() - INTERVAL '6 days'),
    (13, 'হাসান আলী', 5, 'বার্ষিকী স্প্লিট প্যানেল প্যানোরামা ফটোর জন্য পারফেক্ট। তিন প্যানেল সোজা লাইনে বসে, গ্যাপ ২ ইঞ্চি রেখেছিলাম গাইড অনুযায়ী। বিয়ের ছবি ২০১৮ এর, তবু প্রিন্ট স্পষ্ট। অতিথি ঘরে ঢোকার সাথে দেখে প্রশংসা করে।', true, NOW() - INTERVAL '5 days'),
    (13, 'Elena Rodriguez', 5, 'Three panels align well and packaging prevented bends. We sent a wide beach photo from our anniversary trip. Colours true to the file we uploaded. Installation took two people but instructions clear. Looks like a professional gallery wall now.', true, NOW() - INTERVAL '4 days'),
    (14, 'নাফিসা ইসলাম', 5, 'কিডস রুমের ইউনিকর্ন আর্ট বাচ্চার খুব পছন্দ — প্রতিদিন দেখে হাসে। রঙ উজ্জ্বল, কিন্তু cheap প্লাস্টিক লুক নেই। স্টাডি টেবিলের উপরে লাগিয়েছি, সাইজ ঠিক। বন্ধু মায়েরাও লিংক চেয়েছে। দ্রুত ডেলিভারি, ঢাকায় দুই দিন।', true, NOW() - INTERVAL '3 days'),
    (14, 'Rakib Hasan', 5, 'Bright colours and child-safe feel — no strong chemical smell when opened. Hung above study desk as suggested. My daughter is seven and loves the unicorn theme. Print edges clean. Good value compared to local print shops I quoted.', true, NOW() - INTERVAL '3 days'),
    (15, 'পলাশ মিয়া', 4, 'ডাইনোসর থিম আমার ছেলে কাঁদছিল না, এখন রুমে খেলতে খেলতে দেখে। পোস্টার সেট মোটা কাগজ, টেয়ার টেয়ার করে লাগানো যায়। একটায় ছোট স্ক্র্যাচ ছিল, সাপোর্ট বললো রিপ্লেসমেন্ট পাঠাবে — সেবা ভালো। সামগ্রিকভাবে খুশি।', true, NOW() - INTERVAL '2 days'),
    (15, 'Anika Sultana', 5, 'Dino poster set is fun and paper thicker than expected. My twins pick their favourite dinosaur each night. Easy peel stickers for the wall without damaging paint so far. Arrived rolled in a tube not folded — big plus.', true, NOW() - INTERVAL '2 days'),
    (16, 'শিবলী রহমান', 5, 'মেয়ের নাম সহ প্রিন্সেস আর্ট — পার্সোনালাইজেশন একদম ঠিক, বানান ভুল নেই। আটটা থিম থেকে বেছে নিয়েছি, প্রিভিউ দেখে কনফার্ম করেছি। জন্মদিনে উপহার দিয়েছি, ও খুব খুশি। প্রিন্ট রঙ মিষ্টি গোলাপী, রুমের সাদা দেয়ালে মানিয়েছে।', true, NOW() - INTERVAL '1 day'),
    (16, 'Chris Taylor', 4, 'Eight themes to pick from is great and colours match the preview online. Personalised name printed clearly. Delivery to Sylhet took five days. Daughter uses it as room focal point. Only wish framing option existed on checkout.', true, NOW() - INTERVAL '1 day'),
    (17, 'ওয়ালিউল হক', 4, 'অফিসে মোটিভেশনাল পোস্টার টিমের মনোযোগ ধরে রাখে, মিটিং রুমে লাগানো। A2 সাইজ টেক্সট পড়তে স্পষ্ট, দূর থেকেও বোঝা যায়। কাগজ ম্যাট ফিনিশ, গ্ল্যারে কম। ম্যানেজার বললেন আরও একটা অর্ডার করবেন।', true, NOW() - INTERVAL '12 hours'),
    (17, 'Farhana Begum', 5, 'A2 সাইজ ডেস্কের পাশে দারুণ লাগে, টেক্সট পড়তে স্পষ্ট। আমি HR, নতুন জয়েন করা টিমের জন্য মোটিভেশন ওয়াল বানিয়েছি। প্রিন্ট কালো সাদা কনট্রাস্ট ভালো। দুই দিনে পেয়েছি মোহাম্মদপুরে।', true, NOW() - INTERVAL '8 hours'),
    (18, 'সুমন কর্মকার', 5, 'টিমওয়ার্ক ক্যানভাস মিটিং রুমে প্রফেশনাল লুক দিয়েছে। রঙ নিউট্রাল, অফিস ডেকোরের সাথে মিশে যায়। ক্লায়েন্ট আসলে প্রশংসা করেছে। ক্যানভাস টাইট, ফ্রেম ছাড়াই ঝুলিয়েছি, মিনিমাল লুক। WallNest থেকে দ্বিতীয় অর্ডার।', true, NOW() - INTERVAL '5 hours'),
    (18, 'Michael Brown', 4, 'Neutral colours fit our corporate wall in Gulshan office. Good value for a large motivational piece. Shipping box was heavy duty. Text is motivational without being cheesy. Team photo beside it looks coordinated now.', true, NOW() - INTERVAL '2 hours')
) AS d(legacy_id, reviewer_name, rating, comment, is_verified, created_at)
  ON p.legacy_id = d.legacy_id;
